name: deploy
on:
  push:
    branches:
      - main
      - development
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: github-pages
  cancel-in-progress: true
jobs:
  pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v6
        with:
          ref: main
          path: production
      - name: Checkout development
        uses: actions/checkout@v6
        with:
          ref: development
          path: development
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: development/package.json
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: |
            production/pnpm-lock.yaml
            development/pnpm-lock.yaml
      - name: Build development
        working-directory: development
        run: pnpm install --frozen-lockfile && pnpm run build && pnpm run --filter docs build
        env:
          VITE_CUSTOM_HTML_FILE: ${{ github.workspace }}/development/.github/pages/custom.html
          DOCUSAURUS_BASE_URL: /${{ github.event.repository.name }}/docs-dev/
          TISSUUMAPS_APP_URL: https://tissuumaps.github.io/${{ github.event.repository.name }}/live-dev/
      - name: Build production
        working-directory: production
        run: pnpm install --frozen-lockfile && pnpm run build && pnpm run --filter docs build
        env:
          VITE_CUSTOM_HTML_FILE: ${{ github.workspace }}/development/.github/pages/custom.html
          DOCUSAURUS_BASE_URL: /${{ github.event.repository.name }}/docs/
          TISSUUMAPS_APP_URL: https://tissuumaps.github.io/${{ github.event.repository.name }}/live/
      - name: Prepare deployment
        run: |
          mkdir _site
          mv production/apps/tissuumaps/dist _site/live
          mv production/apps/docs/build _site/docs
          mv development/apps/tissuumaps/dist _site/live-dev
          mv development/apps/docs/build _site/docs-dev
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
